#!/bin/bash

# install snippets

cd jupyter-boilerplate-converter
git clone git://github.com/moble/jupyter_boilerplate
npm install

export SNIPPET_DIR=`python -c "from jupyter_core.paths import jupyter_path;print(jupyter_path('snippets')[0])"`

mkdir -p $SNIPPET_DIR

npm run convert ./jupyter_boilerplate/snippets_submenus_python/astropy.js $SNIPPET_DIR .py
npm run convert ./jupyter_boilerplate/snippets_submenus_python/matplotlib.js $SNIPPET_DIR .py
npm run convert ./jupyter_boilerplate/snippets_submenus_python/numpy.js $SNIPPET_DIR .py
npm run convert ./jupyter_boilerplate/snippets_submenus_python/python.js $SNIPPET_DIR .py
npm run convert ./jupyter_boilerplate/snippets_submenus_python/scipy.js $SNIPPET_DIR .py
npm run convert ./jupyter_boilerplate/snippets_submenus_python/h5py.js $SNIPPET_DIR .py
npm run convert ./jupyter_boilerplate/snippets_submenus_python/numba.js $SNIPPET_DIR .py
npm run convert ./jupyter_boilerplate/snippets_submenus_python/sympy.js $SNIPPET_DIR .py

cd ../binder

ln -s $SNIPPET_DIR snippets_symlink

# prepare Jupyter Lab

jupyter lab build

