#!/usr/bin/env sh
""" perform a development install of jupyterlab-snippets
    On Binder, this will run _after_ the environment has been fully created from
    the environment.yml in this directory.
"""

cd jupyter-boilerplate-converter
git clone git://github.com/moble/jupyter_boilerplate
npm install

export SNIPPET_DIR=`python -c "from jupyter_core.paths import jupyter_path;print(jupyter_path('snippets')[0])"`

mkdir -p $SNIPPET_DIR

npm run convert ./jupyter_boilerplate/snippets_submenus_python/astropy.js $SNIPPET_DIR .py
npm run convert ./jupyter_boilerplate/snippets_submenus_python/matplotlib.js $SNIPPET_DIR .py
npm run convert ./jupyter_boilerplate/snippets_submenus_python/numpy.js $SNIPPET_DIR .py
npm run convert ./jupyter_boilerplate/snippets_submenus_python/python.js $SNIPPET_DIR .py
npm run convert ./jupyter_boilerplate/snippets_submenus_python/scipy.js $SNIPPET_DIR .py
npm run convert ./jupyter_boilerplate/snippets_submenus_python/h5py.js $SNIPPET_DIR .py
npm run convert ./jupyter_boilerplate/snippets_submenus_python/numba.js $SNIPPET_DIR .py
npm run convert ./jupyter_boilerplate/snippets_submenus_python/sympy.js $SNIPPET_DIR .py

cd ../binder

ln -s $SNIPPET_DIR snippets_symlink

cd ..

# verify the environment is self-consistent before even starting
python -m pip check

# install the labextension
python -m pip install .

# verify the environment the extension didn't break anything
python -m pip check

# list the extensions
jupyter server extension list

# initially list installed extensions to determine if there are any surprises
jupyter labextension list


echo "JupyterLab with jupyterlab-snippets is ready to run with:"
echo "    jupyter lab"